version: '3.8'

services:
  backend-user:
    image: backend-user:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        NODE_ENV: production
        PORT: ${PORT}
    container_name: backend-user
    network_mode: bridge
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: always
    ports:
      - ${PORT}:3000
    env_file:
      - .env
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
